services:
  external_source:
    build: ./StockDataExternalSource/StockDataExternalSource/
    ports: 
      - "5221:5221"
    environment:
      - MARKET_STACK_API_KEY=${MARKET_STACK_API_KEY?error} 
# NB currently needs host environmental var exported, and docker compose 
# run with -E flag.

